### ISSUE TITLE
反应两个问题

### ISSUE THREAD

**Issue by setube** [meowtec/Imagine#127]
### 软件版本
0.6.1

### 操作系统
Windows 10 x64

### BUG
1.软件每次启动很慢
2.如果当前软件在运行,再点一次运行的话,会无法导入图片或者其他,需要关闭软件重新打开才能正常导入
另外,提几个其他压缩都有的功能,对版本更新可能会有帮助,望采纳

### 意见
1.在用户压缩过图片后,能不能加一个是否删除原图的选项呢?或者说在设置里让用户自己决定是否删除,并让用户决定是一次性的决定还是永久性的决定
2.给用户提供压缩后图片分辨率的改变,比方说原图是1000 * 1000的图片,但是我只想要50 * 50的分辨率,,那么我们是不是可以提供给用户一个这么个解决方案呢?这样用户就不用先去改变分辨率再来打开软件压缩,我觉得这样可以让用户更加依赖这款软件

### 日志
[2022-04-20 08:55:09.612] [error] Error: spawn C:\Users\19622\AppData\Local\Temp\1sF7eE1sGkG44Dxm9zpuZqGP9Sk\resources\app.asar.unpacked\bin\win\cwebp.exe ENOENT
undefined
    at EventEmitter.i (file:///C:/Users/19622/AppData/Local/Temp/1sF7eE1sGkG44Dxm9zpuZqGP9Sk/resources/app.asar/dist/web/app.js:2:32207)
    at EventEmitter.emit (events.js:315:20)
    at Object.onMessage (electron/js2c/renderer_init.js:91:925)
[2022-04-20 08:55:09.655] [error] Error: spawn C:\Users\19622\AppData\Local\Temp\1sF7eE1sGkG44Dxm9zpuZqGP9Sk\resources\app.asar.unpacked\bin\win\cwebp.exe ENOENT
undefined
    at EventEmitter.i (file:///C:/Users/19622/AppData/Local/Temp/1sF7eE1sGkG44Dxm9zpuZqGP9Sk/resources/app.asar/dist/web/app.js:2:32207)
    at EventEmitter.emit (events.js:315:20)
    at Object.onMessage (electron/js2c/renderer_init.js:91:925)
[2022-04-20 08:55:09.694] [error] Error: spawn C:\Users\19622\AppData\Local\Temp\1sF7eE1sGkG44Dxm9zpuZqGP9Sk\resources\app.asar.unpacked\bin\win\cwebp.exe ENOENT
undefined
    at EventEmitter.i (file:///C:/Users/19622/AppData/Local/Temp/1sF7eE1sGkG44Dxm9zpuZqGP9Sk/resources/app.asar/dist/web/app.js:2:32207)
    at EventEmitter.emit (events.js:315:20)
    at Object.onMessage (electron/js2c/renderer_init.js:91:925)
[2022-04-20 08:55:21.237] [error] Error: spawn C:\Users\19622\AppData\Local\Temp\1sF7eE1sGkG44Dxm9zpuZqGP9Sk\resources\app.asar.unpacked\bin\win\cwebp.exe ENOENT
undefined
    at EventEmitter.i (file:///C:/Users/19622/AppData/Local/Temp/1sF7eE1sGkG44Dxm9zpuZqGP9Sk/resources/app.asar/dist/web/app.js:2:32207)
    at EventEmitter.emit (events.js:315:20)
    at Object.onMessage (electron/js2c/renderer_init.js:91:925)
[2022-04-20 08:55:21.275] [error] Error: spawn C:\Users\19622\AppData\Local\Temp\1sF7eE1sGkG44Dxm9zpuZqGP9Sk\resources\app.asar.unpacked\bin\win\cwebp.exe ENOENT
undefined
    at EventEmitter.i (file:///C:/Users/19622/AppData/Local/Temp/1sF7eE1sGkG44Dxm9zpuZqGP9Sk/resources/app.asar/dist/web/app.js:2:32207)
    at EventEmitter.emit (events.js:315:20)
    at Object.onMessage (electron/js2c/renderer_init.js:91:925)
[2022-04-20 08:55:21.314] [error] Error: spawn C:\Users\19622\AppData\Local\Temp\1sF7eE1sGkG44Dxm9zpuZqGP9Sk\resources\app.asar.unpacked\bin\win\cwebp.exe ENOENT
undefined
    at EventEmitter.i (file:///C:/Users/19622/AppData/Local/Temp/1sF7eE1sGkG44Dxm9zpuZqGP9Sk/resources/app.asar/dist/web/app.js:2:32207)
    at EventEmitter.emit (events.js:315:20)
    at Object.onMessage (electron/js2c/renderer_init.js:91:925)

**Comment by meowtec** [comment]
底层在重写，启动慢点情况有望解决，压缩尺寸的功能应该会加进去。
BUG 2 等搞完了我再看看吧。
覆盖原图不就相当于删除原图吗？除非大量图片都是从一种格式到另一种格式，这种情况无法真正覆盖。

**Comment by SeTube** [comment]
> 

我的意思是,处理后的格式与处理前的格式不一,然后用户勾选的情况下,自动删除原格式
就比如说,原图格式是jpg,处理过后的格式是webp,然后自动删除jpg格式的图片
