### ISSUE TITLE
0.11 win10 无法优化, 质量或者色彩调整,无任何反映 

### ISSUE THREAD

**Issue by ptsa** [meowtec/Imagine#9]
0.11 win10 无法优化, 质量或者色彩调整,无任何反映
优化后里面没有图片显示

**Comment by meowtec** [comment]
日志目录：
C:\\Users\username\AppData\Roaming\imagine\log.log

看下报错日志

**Comment by meowtec** [comment]
试了下，Windows 10 确实不行。

**Comment by ptsa** [comment]
[2017-07-01 00:01:04:0723] [error] Error: spawn C:\Users\stxws\AppData\Local\Programs\Imagine\resources\app.asar.unpacked\node_modules\pngquant-bin\vendor\pngquant.exe ENOENT
undefined
    at child_process_promise_1.spawn.catch.e (C:\Users\stxws\AppData\Local\Programs\Imagine\resources\app.asar\lib\optimizers\pngquant.js:18:19)
    at process._tickCallback (internal/process/next_tick.js:103:7)

[2017-07-01 00:02:22:0041] [error] Error: spawn C:\Users\stxws\AppData\Local\Programs\Imagine\resources\app.asar.unpacked\node_modules\mozjpeg\vendor\cjpeg.exe ENOENT
undefined
    at child_process_promise_1.spawn.catch.e (C:\Users\stxws\AppData\Local\Programs\Imagine\resources\app.asar\lib\optimizers\mozjpeg.js:19:19)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by meowtec** [comment]
@ptsa 嗯，我也看到了。我还在搞 Windows 10 虚拟机的开发环境

**Comment by meowtec** [comment]
0.1.1 应该是 build 有 bug，我是在 Windows7 上面 build 的。今天在 Windows 10 上试了下是 OK 的。
这个是新编译的版本，我测试是 OK 的，帮忙测下？如果正常我就发掉了。
http://7qn7vf.com1.z0.glb.clouddn.com/Imagine-Setup-0.1.2.exe

**Comment by ptsa** [comment]
已经可以正常用了, 建议可以设置 默认调整,比如现在jpg 是 70%  ,可以让用户调,

**Comment by meowtec** [comment]
@ptsa 这个功能我是有想过的，具体交互还没想好。
